### ISSUE TITLE
Harvey doesn't like my name (ć)

### ISSUE THREAD

**Issue by davidknezic** [architv/harvey#11]
I get the following result when I run `harvery mit`:

``` sh
Traceback (most recent call last):
  File "/usr/local/bin/harvey", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/harvey/harvey.py", line 163, in main
    print(_get_license_description(arguments['<NAME>'].lower()))
  File "/usr/local/lib/python2.7/site-packages/harvey/harvey.py", line 86, in _get_license_description
    license = re.sub(r'\[(.+)\]', replace_string, s)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc4 in position 16: ordinal not in range(128)
```

The reason is the character `ć` in my name. Would be nice if `harvey` was able to handle unicode characters.

**Comment by davidknezic** [comment]
So I read that python3 doesn't treat unicode characters specially anymore which is why I upgraded:

``` sh
pip uninstall harvey
brew install python3
pip3 install harvey
```

But then I still had trouble with `harvey`, which errored with this message:

``` sh
Traceback (most recent call last):
  File "/usr/local/bin/harvey", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/site-packages/harvey/harvey.py", line 163, in main
    print(_get_license_description(arguments['<NAME>'].lower()))
  File "/usr/local/lib/python3.5/site-packages/harvey/harvey.py", line 81, in _get_license_description
    name=_get_config_name())
  File "/usr/local/lib/python3.5/site-packages/harvey/harvey.py", line 58, in _get_config_name
    return _stripslashes(output[0])
  File "/usr/local/lib/python3.5/site-packages/harvey/harvey.py", line 48, in _stripslashes
    r = re.sub(r"\\(n|r)", "\n", s)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/re.py", line 182, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: cannot use a string pattern on a bytes-like object
```

In order to get it working, I had to convert the bytes into a string using that code:

``` py
53: def _get_config_name():
xx:   ...
59:   return _stripslashes(output[0].decode('utf8'))
```

The tool works perfectly now. It would however be nice to see it work seamlessly with unicode characters in python2 and python3 without having to make any patches.

**Comment by jfromaniello** [comment]
Same problem, work with python3 and this patch.
